# Test-only: build a copied external plugin against an installed header-only SDK.
cmake_minimum_required(VERSION 3.25)
foreach(required SOURCE_ROOT TEST_ROOT GENERATOR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(NOT CONFIG)
    set(CONFIG Debug)
endif()
function(checked)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "SDK fixture command failed (${result})\n${output}\n${error}")
    endif()
endfunction()
set(generator_args -G "${GENERATOR}")
if(PLATFORM)
    list(APPEND generator_args -A "${PLATFORM}")
endif()
if(TOOLSET)
    list(APPEND generator_args -T "${TOOLSET}")
endif()
set(prefix "${TEST_ROOT}/sdk-install")
checked("${CMAKE_COMMAND}" -S "${SOURCE_ROOT}/sdk/plugin" -B "${TEST_ROOT}/sdk-build" ${generator_args})
checked("${CMAKE_COMMAND}" --install "${TEST_ROOT}/sdk-build" --prefix "${prefix}" --config "${CONFIG}")
# Copied sources have only their own modules and the installed SDK on include paths.
file(MAKE_DIRECTORY "${TEST_ROOT}/external-example" "${TEST_ROOT}/external-tests")
file(COPY "${SOURCE_ROOT}/examples/plugins/standalone/" DESTINATION "${TEST_ROOT}/external-example")
file(COPY "${SOURCE_ROOT}/tests/plugin_sdk/" DESTINATION "${TEST_ROOT}/external-tests")
# Model a normal Windows checkout. Runtime and packaged descriptions must agree
# even when the developer's source JSON uses CRLF rather than LF.
file(READ "${TEST_ROOT}/external-example/nodes.json" source_nodes)
string(REPLACE "\r\n" "\n" source_nodes "${source_nodes}")
string(REPLACE "\n" "\r\n" checkout_nodes "${source_nodes}")
file(WRITE "${TEST_ROOT}/external-example/nodes.json" "${checkout_nodes}")
checked("${CMAKE_COMMAND}" -S "${TEST_ROOT}/external-example" -B "${TEST_ROOT}/plugin-build"
    ${generator_args} "-DCMAKE_PREFIX_PATH=${prefix}")
checked("${CMAKE_COMMAND}" --build "${TEST_ROOT}/plugin-build" --config "${CONFIG}" --parallel 2)
set(plugin "${TEST_ROOT}/plugin-build/package/${CONFIG}/ag_example_plugin.dll")
if(NOT EXISTS "${plugin}")
    message(FATAL_ERROR "Standalone plugin package was not produced: ${plugin}")
endif()
# Check this fixture's package metadata without loading code or interpreting it
# as a production manifest schema. Installation/policy checks remain future work.
get_filename_component(package_dir "${plugin}" DIRECTORY)
file(READ "${package_dir}/manifest.json" manifest)
string(JSON architecture GET "${manifest}" architecture)
string(JSON entry GET "${manifest}" entry)
string(JSON entry_hash GET "${manifest}" files 0 sha256)
string(JSON nodes_hash GET "${manifest}" files 1 sha256)
file(SHA256 "${plugin}" actual_entry_hash)
file(SHA256 "${package_dir}/nodes.json" actual_nodes_hash)
if(NOT architecture STREQUAL "x86_64" OR NOT entry STREQUAL "ag_example_plugin.dll"
   OR NOT actual_entry_hash STREQUAL entry_hash OR NOT actual_nodes_hash STREQUAL nodes_hash)
    message(FATAL_ERROR "Example package platform or file fingerprints disagree")
endif()
checked("${CMAKE_COMMAND}" -S "${TEST_ROOT}/external-tests" -B "${TEST_ROOT}/host-build"
    ${generator_args} "-DCMAKE_PREFIX_PATH=${prefix}" "-DAG_TEST_PLUGIN_PATH=${plugin}")
checked("${CMAKE_COMMAND}" --build "${TEST_ROOT}/host-build" --config "${CONFIG}" --parallel 2)
execute_process(COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${TEST_ROOT}/host-build"
    -C "${CONFIG}" --output-on-failure RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
message(STATUS "${output}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Independent SDK contract tests failed: ${error}")
endif()
