if(NOT DEFINED PLUGIN_FILE OR NOT EXISTS "${PLUGIN_FILE}")
    message(FATAL_ERROR "The built plugin entry is missing")
endif()
if(NOT DEFINED NODES_FILE OR NOT EXISTS "${NODES_FILE}" OR NOT DEFINED PACKAGE_DIR)
    message(FATAL_ERROR "The plugin package inputs are incomplete")
endif()
get_filename_component(ENTRY "${PLUGIN_FILE}" NAME)
file(MAKE_DIRECTORY "${PACKAGE_DIR}")
file(COPY_FILE "${PLUGIN_FILE}" "${PACKAGE_DIR}/${ENTRY}" ONLY_IF_DIFFERENT)
file(COPY_FILE "${NODES_FILE}" "${PACKAGE_DIR}/nodes.json" ONLY_IF_DIFFERENT)
file(SHA256 "${PACKAGE_DIR}/${ENTRY}" ENTRY_SHA256)
file(SHA256 "${PACKAGE_DIR}/nodes.json" NODES_SHA256)
configure_file("${CMAKE_CURRENT_LIST_DIR}/manifest.json.in" "${PACKAGE_DIR}/manifest.json" @ONLY)
